group = dev.lewischan

## Use Kotlin official code style
kotlin.code.style = official

## GitHub CodeQL auto build requires a higher than default size
kotlin.daemon.jvmargs=-Xmx2g

## Annotation processor dependencies that aren't included in the processor path (the kapt* configurations) are excluded from kapt processing
kapt.include.compile.classpath=false
