logging:
  structured:
    format:
      console: ""

management:
  opentelemetry:
    enabled: false
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    export:
      enabled: false
      otlp:
        enabled: false

spring:
  config:
    import: optional:file:.env.development[.properties]
